allowBuilds:
  '@parcel/watcher': true
  core-js: true
  es5-ext: true
  esbuild: true
  vue-demi: true
overrides:
  '@tiptap/extension-floating-menu': 3.31.0
  'stylelint-config-recommended-vue>stylelint-config-html': 1.1.0
